// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ABBMEcJ88e_4pnZT4VzJh2rtxSsIRh8',
    appId: '1:328816099343:web:d7a2eb0cc9a849ae2ba37a',
    messagingSenderId: '328816099343',
    projectId: 'budget-bear',
    authDomain: 'budget-bear.firebaseapp.com',
    storageBucket: 'budget-bear.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM5jDlcT6Qxapp0qWDm9Nrt1IRCykEym4',
    appId: '1:328816099343:android:a9441cf72a5253182ba37a',
    messagingSenderId: '328816099343',
    projectId: 'budget-bear',
    storageBucket: 'budget-bear.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF5naVRgm3FPlgFH9Sjj_ilCcGlr_YI3g',
    appId: '1:328816099343:ios:dc11fffa805262e02ba37a',
    messagingSenderId: '328816099343',
    projectId: 'budget-bear',
    storageBucket: 'budget-bear.firebasestorage.app',
    iosBundleId: 'com.example.budgetBear',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF5naVRgm3FPlgFH9Sjj_ilCcGlr_YI3g',
    appId: '1:328816099343:ios:dc11fffa805262e02ba37a',
    messagingSenderId: '328816099343',
    projectId: 'budget-bear',
    storageBucket: 'budget-bear.firebasestorage.app',
    iosBundleId: 'com.example.budgetBear',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6ABBMEcJ88e_4pnZT4VzJh2rtxSsIRh8',
    appId: '1:328816099343:web:c0ff50f0ddd34ab42ba37a',
    messagingSenderId: '328816099343',
    projectId: 'budget-bear',
    authDomain: 'budget-bear.firebaseapp.com',
    storageBucket: 'budget-bear.firebasestorage.app',
  );
}
